### ISSUE TITLE
Broken handling of periods

### ISSUE THREAD

**Issue by CollinDewey** [nix-community/plasma-manager#8] opened 2022-08-08 09:10 UTC
Unfortunately there are KDE settings with periods in the group name, which leads to incorrect names being sent to kwriteconfig5, and thus the resulting files.

An example of this
`files."kwinrc"."org.kde.kdecoration2"."ButtonsOnRight" = "SBFIAX";`
leads to
```
[org][kde][kdecoration2]
ButtonsOnRight=SBFIAX
```
instead of the desired
```
[org.kde.kdecoration2]
ButtonsOnRight=SBFIAX
```

**Comment by pjones** [comment] 2022-08-08 13:51
This is also related to 2146ecadc440f1949fd0780c3fa7123693909a69.

The problem is that there are a few KDE settings that use nested groups and I decided to generate those when the group name contains periods.  But then it turns out there there are a few groups that have actual periods in their names!  I probably need to give up on using a period in Nix to generate the nested groups.

I suppose a forward slash would be the next best character.

**Comment by toast003** [comment] 2023-10-20 11:33
I'm confused, isn't https://github.com/pjones/plasma-manager/commit/2146ecadc440f1949fd0780c3fa7123693909a69 supposed to fix this?
That's what I got from the description at least

**Comment by magnouvean** [comment] 2023-12-18 12:07
Looking at that commit it looks like it was supposed to solve it, but this still is a problem it seems like. A proposed solution though is just allowing escaping periods, so that we would use:
```nix
files."kwinrc"."org\.kde\.kdecoration2"."ButtonsOnRight" = "SBFIAX";
```
instead as proposed in https://github.com/pjones/plasma-manager/issues/33. This should allow for us to combine nested groups and keys with periods, where the keys with periods would just need to be escaped. In which case https://github.com/pjones/plasma-manager/pull/34 should solve this.

**Comment by magnouvean** [comment] 2023-12-18 12:32
This should be available now by manually escaping the periods using "\\.". I.e. you should be able to do:
```
files."kwinrc"."org\\.kde\\.kdecoration2"."ButtonsOnRight" = "SBFIAX";
```
Closing this now, but if there are any great difficulties with this solution feel free to reopen.

**Closed as completed by magnouvean** 2023-12-18 12:32 UTC
