### ISSUE TITLE
rc2nix failing?

### ISSUE THREAD

**Issue by drupol** [nix-community/plasma-manager#4] opened 2022-07-03 09:23 UTC
Hi,

I would like to give this project a try and I tried to run the tool `rc2nix` and it's failing:

```
$ nix run github:pjones/plasma-manager                                                                                                                                                                                                   
Traceback (most recent call last):
        4: from /nix/store/3nibd0z57l85g2x83wmyqr0yxqyqycdr-rc2nix.rb:216:in `<main>'
        3: from /nix/store/3nibd0z57l85g2x83wmyqr0yxqyqycdr-rc2nix.rb:130:in `run'
        2: from /nix/store/3nibd0z57l85g2x83wmyqr0yxqyqycdr-rc2nix.rb:130:in `each'
        1: from /nix/store/3nibd0z57l85g2x83wmyqr0yxqyqycdr-rc2nix.rb:136:in `block in run'
/nix/store/n8gvlg12cmxw3a37nvbafhri9pp4l494-ruby-2.7.6/lib/ruby/2.7.0/pathname.rb:522:in `relative_path_from': different prefix: "/" and "~/.config" (ArgumentError)
$
```

Am I doing something wrong?

**Comment by pjones** [comment] 2022-07-03 17:08
@drupol: Looks like a bug in the script.  Can you tell me what your `XDG_CONFIG_HOME` environment variable is set to:

```sh
echo $XDG_CONFIG_HOME
```

Thank you.

**Comment by pjones** [comment] 2022-07-03 17:15
I was able to reproduce and then fix the issue.

Fixed on the main branch.

**Closed as completed** 2022-07-03 17:15 UTC

**Comment by drupol** [comment] 2022-07-03 17:38
Thanks ! it works now !
