### ISSUE TITLE
nix run <plasma-manager> results in a error (setting outside of group: MenuBar=Disabled)

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [nix-community/plasma-manager#415] opened 2024-11-16 23:48 UTC
I get this error whenever I run the command:
 nix run github:nix-community/plasma-manager
```

[spiderunderurbed@daspidercave:~]$ nix run github:nix-community/plasma-manager
Traceback (most recent call last):
  File "/nix/store/q577g3687yhlzf130ajsj868qcnzldqi-rc2nix.py", line 286, in <module>
    Rc2Nix.App(sys.argv[1:]).run()
  File "/nix/store/q577g3687yhlzf130ajsj868qcnzldqi-rc2nix.py", line 190, in run
    rc.parse()
  File "/nix/store/q577g3687yhlzf130ajsj868qcnzldqi-rc2nix.py", line 143, in parse
    self.process_setting(key, val)
  File "/nix/store/q577g3687yhlzf130ajsj868qcnzldqi-rc2nix.py", line 162, in process_setting
    raise Exception(
Exception: /home/spiderunderurbed/.config/dolphinrc: setting outside of group: MenuBar=Disabled

```

**Comment by HeitorAugustoLN** [comment] 2024-11-19 19:59
This is happening because `rc2nix` doesn't read settings that don't have a group. Neither can plasma-manager write them as of now. But I will probably work on this.

**Comment by HeitorAugustoLN** [comment] 2024-11-30 20:55
I will close this since this is a duplicate of #17. Any further discussions can be done there.

**Closed as not planned by HeitorAugustoLN** 2024-11-30 20:55 UTC
