### ISSUE TITLE
syntax error near unexpected token `('

### ISSUE THREAD

**Issue by ByteSudoer** [nix-community/plasma-manager#43] opened 2024-01-03 11:03 UTC
here is my nix-info:
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.11 (Tapir), 23.11.20231231.32f6357`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/pi7hsz4pfhw0m3a4nv7qwjjfdx70m7hh-source`
 Here is my plasma-config after running `nix run github:pjones/plasma-manager > home/desktop/config/plasma/default.nix` in this pastebin.link https://pastebin.com/gKf0k9ec
##The error messages are down bellow:
when doing a system rebuild i get the following errors
- Jan 03 11:52:03 nixos hm-activate-bytesudoer[19551]: /nix/store/bhrwiq9c3zb9z7il5alfmfq9msyxi6pv-plasma-config: line 1: syntax error near unexpected token `('
- Jan 03 11:52:03 nixos hm-activate-bytesudoer[19551]: /nix/store/bhrwiq9c3zb9z7il5alfmfq9msyxi6pv-plasma-config: line 1: `/nix/store/sxi0q32x7dwjw4j3qbc5dfzhcywlwb2k-writ>
- Jan 03 11:52:03 nixos hm-activate-bytesudoer[19551]: GroupNesting":["Data_3_6Actions"]},"Data_3_6Actions0":{"DestinationWindow":2,"Input":"Ctrl+W\n","Type":"KEYBOARD_INP>
- Jan 03 11:52:03 nixos systemd[1]: home-manager-bytesudoer.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Thx in advance

**Comment by hatch01** [comment] 2024-01-03 17:35
same probleme !
here is my config : 
```nix
{ config, pkgs, ...}:

{
  programs.plasma = {
    enable = true;

    shortcuts = {
      ksmserver = {
        "Lock Session" = "Meta+L";
      };
      kwin = {
        "Switch One Desktop Down" = "Meta+Shift+Down";
        "Switch One Desktop Up" = "Meta+Shift+Up";
        "Switch One Desktop to the Left" = "Meta+Shift+Left";
        "Switch One Desktop to the Right" = "Meta+Shift+Right";
        "Switch Window Down" = [ ];
        "Switch Window Left" = "Meta+Alt+Left";
        "Switch Window Right" = "Meta+Alt+Right";
        "Switch Window Up" = [ ];
        "Switch to Desktop 1" = "Meta+&";
        "Switch to Desktop 2" = "Meta+É";
        "Switch to Desktop 3" = "Meta+\"";
        "Switch to Desktop 4" = "Meta+'";
        "Switch to Desktop 5" = "Meta+(";
        "Switch to Desktop 6" = "Meta+-";
        "Switch to Desktop 7" = "Meta+È";
        "Switch to Desktop 8" = "Meta+_";
        "Switch to Desktop 9" = "Meta+ç";
        "Switch to Desktop 10" = "Meta+à";
        "Window Maximize" = "Meta+Ctrl+Up";
        "Window Minimize" = "Meta+Ctrl+Down";
        "Window to Desktop 1" = "Meta+1";
        "Window to Desktop 2" = "Meta+2";
        "Window to Desktop 3" = "Meta+3";
        "Window to Desktop 4" = "Meta+4";
        "Window to Desktop 5" = "Meta+5";
        "Window to Desktop 6" = "Meta+6";
        "Window to Desktop 7" = "Meta+7";
        "Window to Desktop 8" = "Meta+8";
        "Window to Desktop 9" = "Meta+9";
        "Window to Desktop 10" = "Meta+0";
        "Window to Next Screen" = [ ];
        "Window to Previous Screen" = [ ];
        "Window to Screen 0" = "Meta+Ctrl+1";
        "Window to Screen 1" = "Meta+Ctrl+2";
        "view_zoom_in" = "Meta+Ctrl++";
        "view_zoom_out" = "Meta+Ctrl+-";
      };
      "yakuake"."toggle-window-state" = "Meta+Return";
    };
    configFile = {
      "kcminputrc"."Libinput.1739.52861.SYNA32B9:00 06CB:CE7D Touchpad"."NaturalScroll" = true;
      "kcminputrc"."Libinput.1739.52861.SYNA32B9:00 06CB:CE7D Touchpad"."TapToClick" = true;
      "krunnerrc"."General"."FreeFloating" = true;
      "plasma-org.kde.plasma.desktop-appletsrc" = {
        "Containments.2.Applets.30" = {
          "immutability" = 1;
          "plugin" = "day-night-switcher";
        };
        "Containments.37.Applets.62" = {
          "immutability" = 1;
          "plugin" = "day-night-switcher";
        };

        "Containments.2.Applets.31.Configuration.General" = {
          "customButtonImage" = "nix-snowflake";
          "favoritesPortedToKAstats" = true;
          "systemFavorites" = "suspend\\,hibernate\\,reboot\\,shutdown";
          "useCustomButtonImage" = true;
        };
        "Containments.2.Applets.5.Configuration.General"."groupedTaskVisualization" = 2;
      };

        "plasma-org.kde.plasma.desktop-appletsrc"."Containments.1.Wallpaper.org\\.kde\\.potd.General" = {
          "FillMode" = 2;
          "Provider" = "unsplash";
        };
        "plasma-org.kde.plasma.desktop-appletsrc"."Containments.34.Wallpaper.org\\.kde\\.potd.General" = {
          "FillMode" = 2;
          "Provider" = "unsplash";
        };

# desktop configs
      "kwinrc"."Windows"."RollOverDesktops" = true;
      "kwinrc"."Desktops" = {
        "Number" = 10;
        "Rows" = 2;
      };
      "kwinrc"."Effect-slide" = {
        "HorizontalGap" = 0;
        "VerticalGap" = 0;
      };

# keepassxc
      "keepassxc/keepassxc.ini"."SSHAgent"."Enabled"=true; 
      "keepassxc/keepassxc.ini"."FdoSecrets"."Enabled"=true; 
      "keepassxc/keepassxc.ini"."General"."HideWindowOnCopy"=true; 
      "kwalletrc"."org\.freedesktop\.secrets"."apiEnabled" = false;

#mime apps WARNING DONT FORGET ; IN THE STRING
      "mimeapps.list"."Added Associations" = {
        "text/markdown" = "org.kde.ghostwriter.desktop;";
      };
    };
  };

# autostart keepassxc
  home.file.".config/autostart/" = {
    source = ./autostart;
    force = true;
    recursive = true;
  };

  home.file.".local/share/plasma/plasmoids/day-night-switcher" = {
    source = ./day-night-switcher;
    recursive = true;
    force = true;
  };
}
```

**Comment by hatch01** [comment] 2024-01-04 09:21
@magnouvean it's probably due to your PR here : #39

**Comment by magnouvean** [comment] 2024-01-04 09:51
Yeah it probably is due to some minor problem in my config-writing script. I merged it maybe a bit early because it ran without problems on my config. Looking into this now. There appears to be some entry in the `configFile` section given above which causes the program to fail.

**Comment by magnouvean** [comment] 2024-01-04 11:10
It appears the problem is how json is sent to the configuration-writing script, where some symbols seem to cause problems. I have looked at some ways to solve this but haven't found any easy solution yet, but I'll try a little more later when I have time. Hopefully shouldn't take that long to find a fix. Until then you can of course use "github:pjones/plasma-manager/e9f464e016e3afa7b23f37b5e5e61216f964cbeb" as the plasma-manager url as that should still work fine (this doesn't convert anything to json, but of course has some other limitations).

**Comment by hatch01** [comment] 2024-01-04 12:54
Thank you for your quick looks. Plasma-manager works very well on e9f464e016e3afa7b23f37b5e5e61216f964cbeb, so the problem is not dramatic.
If it could help is here a small trick I used to allow escaping char #34 .

**Comment by magnouvean** [comment] 2024-01-04 15:37
I think I figured it out now. The problem was mainly caused by the symbols ' in @hatch01's config and \n in @ByteSudoer 's config. I solved it by just writing the json to a file and send the filepath in as an argument instead. I tested both of the configs above and none of them gave an error as far as I could see. Could anyone test using plasma-manager url https://github.com/magnouvean/plasma-manager just to confirm that everything is good. If so I'll create a pr and merge swiftly :)

**Comment by hatch01** [comment] 2024-01-04 15:46
I tested on my system and saw no problems!

**Comment by ByteSudoer** [comment] 2024-01-04 15:47
Same here everything worked flawlessly . I will mark this issue as solved.Thx

**Closed as completed** 2024-01-04 15:47 UTC

**Comment by hatch01** [comment] 2024-01-04 15:49
```nix    
# Writing to file handles special characters better than passing it in as
    # an argument to the script.
    jsonFile = pkgs.writeText "data.json" jsonStr;```
this seems very strange that nix handle better while writing in a file.

**Comment by magnouvean** [comment] 2024-01-04 15:56
Great I will merge immediately :). I think the reason why it was problematic was that if the json string had a ' or \n that the starting ' would be closed, or a new line would be started, which gave all sorts of error for the shell. Thus it's not really a nix-problem, but rather how we sent in a nix-expression as json string via a normal command line argument without considering special characters. Thus by writing to a file instead we get rid of this problem, as sending in a filepath as a command-line argument is unproblematic.
